### ISSUE TITLE
error in GLMestimatesingletrial.m 

### ISSUE THREAD

**Issue by khazarAhmadi** [cvnlab/GLMsingle#91] opened 2023-05-25 17:05 UTC
Hi, 

Thank you for creating a great toolbox! 
I am trying to run the MATLAB implementation of GLMsingle. I have 3 fMRI runs each of which contains 72 volumes with TR of 2.5 s. 16 animal images are presented in each run consisting of 4 animal types, each with 4 distinct examples (4 X 4 duration of each stimulus = TR). I am only interested in estimating betas for images that were correctly recalled as 'old' during the retrieval task. So, in run 1, there are 12 images, in run 2 15 images and in runs 3, 16 images that were successfully retrieved at the end in one participant (43 images in total that were presented only once; see the attached image). When I run the GLMestimatesingletrial.m with default parameters, it crashes with the following error message " Error using  ./ 
Arrays have incompatible sizes for this operation.
Error in GLMestimatesingletrial>calcdmetric (line 1568)
f = sqrt(mean(tempmn.^2,4)) ./ sqrt(mean(tempsd.^2,4))"

A bit of debugging turned out that 'tempsd' is empty since the former 'if' condition is not met. In line 1563, the length of 'ix' is not greater than 1, but is always equal to 1 which results in code crash. I also looked at the example dataset for comparison. There, an image is sometimes presented more than once, thus length(ix) > 1 and the code works just fine with the example data. Shall I change the design matrix such that 4 types of animals in 3 runs make 12 conditions with several repeats? Note that although certain images belong to the same category, they are not identical i.e., there are no repetition.  Any help on how to resolve this issue would be very much appreciated. 

Thanks and best, 
Khazar 

![Xmatrix](https://github.com/cvnlab/GLMsingle/assets/69059866/c089e758-11e1-4de5-a9ec-a79d0c9d1f63)

**Comment by kendrickkay** [comment] 2023-05-26 20:05
Thanks for the detailed explanation.  A few comments:
- One strategy you may wish to try is to code the 4 examples of the same animal type as if they belong to a single condition (as you mentioned). It is true that you ultimately want to distinguish them. From the point of view of GLMsingle, it just relies on gentle assumptions that the 4 examples will approximately give rise to some level of repeatable activation.
- You mentioned analyzing the data according to behavioral performance. One way to do this is to just code all of the various trials, and then posthoc sort and reject trials according to your needs. In other words, you don't have to create a design matrix that has all of the behavioral contingencies.
- I think you picked up on a bug, namely, dmetric is ill defined if the user specifies a design matrix that has no repeats at all. I will fix this.
- Although you can use GLMsingle for the case of no repeats, note that you will have to turn off the GLMdenoise and Ridge Regression (RR) features (as they rely on the existence of repeats). However, as recommended above, if you are willing to code your experiment as if it has some repeats, then you can use the default parameters for GLMsingle (with GLMdenoise + RR).
-

**Comment by kendrickkay** [comment] 2023-06-09 09:32
A few thoughts:
- Yes, GLMsingle should be fine for laminar scale data. (I have run it on 0.8mm 7T data, and it is fine.)
- Regarding your mask mis-alignment, this is likely due to NIFTI header issues. Make sure you preserve NIFTI headers when you save.  E.g. if you use the NIFTI toolbox (load_untouch_nii, etc.), you can inherit an existing NIFTIs headers before doing the save_untouch_nii command.
- Your figure shows a fracvalue that is all 1s.  This is strange.  Did you run GLMsingle with the RR off?
- Regarding why the results look noisy/bad, are you 100% sure about the coding of your design matrix?  Also, if run the MATLAB version, there are some diagnostic figures that are generated. Those can be useful to inspect to understand what might be happening.

**Comment by iancharest** [comment] 2024-05-29 17:17
we will close this issue now, but feel free to reopen if any more errors subsist with GLMestimatesingletrial.

**Closed by iancharest** 2024-05-29 17:17 UTC
